alter table signs add tag1 TEXT;
alter table signs add tag2 TEXT;
alter table signs add tag3 TEXT;
update signs set name_de = "Dann/Danach", mnemonic = "Die Zukunft liegt vor mir", tag1 ="Zeit", tag2 ="Teil 2" where name = "afterwards";
update signs set name_de = "Noch mal", mnemonic = "Gebärde 'eins' kommt von hinten nach vorn", tag1 ="Kleine Worte", tag2 ="Teil 1" where name = "again";
update signs set name_de = "Flugzeug/Fliegen", mnemonic = "Y-Hand startet vom Boden", tag1 ="Fahrzeug", tag2 ="Teil 3" where name = "airplane";
update signs set name_de = "Allah", mnemonic = "Faust öffnet nach vorn", tag1 ="Religion", tag2 ="Teil 3" where name = "allah";
update signs set name_de = "Alleine", mnemonic = "Erhobenen Zeigefinger von oben nach unten ziehen", tag1 ="Kleine Worte", tag2 ="Teil 1" where name = "alone";
update signs set name_de = "Entschuldigung", mnemonic = "Handfläche kreist auf Handrücken", tag1 ="Interaktion", tag2 ="Teil 3" where name = "apology";
update signs set name_de = "Apfel", mnemonic = "Abbeißen", tag1 ="Lebensmittel", tag2 ="Teil 1" where name = "apple";
update signs set name_de = "Geht es dir gut?", mnemonic = "Mit fragender Mimik 'du' und 'gut' gebärden", tag1 ="Interaktion", tag2 ="Teil 2" where name = "are_you_ok";
update signs set name_de = "Auch", mnemonic = "Komma in die Luft malen", tag1 ="Kleine Worte", tag2 ="Teil 1", tag3 ="Interaktion" where name = "as_well";
update signs set name_de = "Baby", mnemonic = "Baby auf Arm schaukeln", tag1 ="Person", tag2 ="Teil 1" where name = "baby";
update signs set name_de = "Schlecht/Doof", mnemonic = "Daumen runter", tag1 ="Eigenschaften", tag2 ="Teil 1" where name = "bad";
update signs set name_de = "Tasche", mnemonic = "Taschengriff ergreifen und hochnehmen", tag1 ="Behälter", tag2 ="Teil 2" where name = "bag";
update signs set name_de = "Backen/Kneten", mnemonic = "Mit Händen kneten", tag1 ="Ernährung", tag2 ="Teil 2", tag3 ="Verb" where name = "baking";
update signs set name_de = "Ball", mnemonic = "Mit Handflächen Ball umfahren", tag1 ="Spielen", tag2 ="Teil 2" where name = "ball";
update signs set name_de = "Banane", mnemonic = "Dominante Hand schält", tag1 ="Lebensmittel", tag2 ="Teil 1" where name = "banana";
update signs set name_de = "Baden", mnemonic = "Rücken mit Handtuch abrubbeln", tag1 ="Körperpflege", tag2 ="Teil 1", tag3 ="Verb" where name = "bathing";
update signs set name_de = "Badezimmer", mnemonic = "Erst 'baden' dann 'Zimmer'", tag1 ="Haus", tag2 ="Teil 3" where name = "bathroom";
update signs set name_de = "Bett", mnemonic = "Kopf legt sich  schlafen", tag1 ="Haus", tag2 ="Teil 1" where name = "bed";
update signs set name_de = "Vorher", mnemonic = "Vergangenheit liegt hinter mir", tag1 ="Zeit", tag2 ="Teil 2", tag3 ="Zeit" where name = "before";
update signs set name_de = "Anfangen", mnemonic = "Eine Arbeit aufnehmen", tag1 ="Arbeit", tag2 ="Teil 2", tag3 ="Verb" where name = "begin";
update signs set name_de = "Unter", mnemonic = "Handrücken unter Handfläche legen", tag1 ="Kleine Worte", tag2 ="Teil 2", tag3 ="Präposition" where name = "below";
update signs set name_de = "Groß", mnemonic = "Hände maximal breit auseinander", tag1 ="Eigenschaften", tag2 ="Teil 3" where name = "big";
update signs set name_de = "Fahrrad", mnemonic = "Fäuste fahren", tag1 ="Fahrzeug", tag2 ="Teil 3" where name = "bike";
update signs set name_de = "Vogel", mnemonic = "Schnabel auf und zu", tag1 ="Tier", tag2 ="Teil 2" where name = "bird";
update signs set name_de = "Pflanze/blühen", mnemonic = "Pflanze wächst aus Boden/neben Körper", tag1 ="Natur", tag2 ="Teil 2" where name = "bloom";
update signs set name_de = "Blau", mnemonic = "Fluss von oben nach unten schlängeln", tag1 ="Farbe", tag2 ="Teil 3", tag3 ="Eigenschaften" where name = "blue";
update signs set name_de = "Buch", mnemonic = "Handflächen öffnen sich wie Buch", tag1 ="Spielen", tag2 ="Teil 2", tag3 ="Lernen" where name = "book";
update signs set name_de = "Junge", mnemonic = "2x mit gestreckter Hand grüßen", tag1 ="Person", tag2 ="Teil 2" where name = "boy";
update signs set name_de = "Brot", mnemonic = "Eine Scheibe abschneiden", tag1 ="Lebensmittel", tag2 ="Teil 2" where name = "bread";
update signs set name_de = "Kaputt", mnemonic = "Fäuste zerbrechen etwas", tag1 ="Eigenschaften", tag2 ="Teil 3" where name = "broken";
update signs set name_de = "Bürsten/Kämmen", mnemonic = "Faust bürstet über Haare", tag1 ="Körperpflege", tag2 ="Teil 3" where name = "brush_hair";
update signs set name_de = "Zähne putzen", mnemonic = "Zeigefinger putzt Zähne auf und ab", tag1 ="Körperpflege", tag2 ="Teil 3" where name = "brush_teeth";
update signs set name_de = "Buddha", mnemonic = "O-Hände bewegen sich nach vorn", tag1 ="Religion", tag2 ="Teil 3" where name = "buddha";
update signs set name_de = "Bauen/Bauklötze", mnemonic = "Hände stapeln", tag1 ="Spielen", tag2 ="Teil 2" where name = "build";
update signs set name_de = "Bus", mnemonic = "Buslänge zeigen, diagonal", tag1 ="Fahrzeug", tag2 ="Teil 1" where name = "bus";
update signs set name_de = "Butter", mnemonic = "Zeigefinger streicht Butter auf Brot", tag1 ="Lebensmittel", tag2 ="Teil 3" where name = "butter";
update signs set name_de = "Schmetterling", mnemonic = "Hände verhaken und Flügel flattern", tag1 ="Tier", tag2 ="Teil 3" where name = "butterfly";
update signs set name_de = "Kakao", mnemonic = "Daumen tippt 2x an Mundwinkel", tag1 ="Lebensmittel", tag2 ="Teil 2", tag3 ="Getränk" where name = "cacao";
update signs set name_de = "Bonbon", mnemonic = "Bonbon in Wange", tag1 ="Lebensmittel", tag2 ="Teil 1" where name = "candy";
update signs set name_de = "Auto", mnemonic = "lenken mimen", tag1 ="Fahrzeug", tag2 ="Teil 1" where name = "car";
update signs set name_de = "Achtung/Vorsicht", mnemonic = "V-Hände gucken weit zu den Seiten", tag1 ="Interaktion", tag2 ="Teil 3" where name = "careful";
update signs set name_de = "Möhre", mnemonic = "Schrappen", tag1 ="Lebensmittel", tag2 ="Teil 1" where name = "carrot";
update signs set name_de = "Katze", mnemonic = "3 Schnurrhaare andeuten", tag1 ="Tier", tag2 ="Teil 2" where name = "cat";
update signs set name_de = "Stuhl", mnemonic = "Gebeugte Finger  als Lehne", tag1 ="Haus", tag2 ="Teil 1" where name = "chair";
update signs set name_de = "Huhn", mnemonic = "Mit Zeigefinger und Daumen picken", tag1 ="Tier", tag2 ="Teil 3" where name = "chicken";
update signs set name_de = "Kinder", mnemonic = "Köpfe wie Orgelpfeifen zeigen", tag1 ="Person", tag2 ="Teil 1" where name = "children";
update signs set name_de = "Schokolade", mnemonic = "Tafel zeigen", tag1 ="Lebensmittel", tag2 ="Teil 1" where name = "chocolade";
update signs set name_de = "Sauber", mnemonic = "Hand sauber wischen", tag1 ="Eigenschaften", tag2 ="Teil 2" where name = "clean";
update signs set name_de = "Klettern", mnemonic = "Mit Krallhänden nach oben klettern", tag1 ="Freizeit", tag2 ="Teil 3", tag3 ="Verb" where name = "climbing";
update signs set name_de = "Schlüssel/Schließen", mnemonic = "Auf- und zuschließen", tag1 ="Haus", tag2 ="Teil 2", tag3 ="Verb" where name = "close";
update signs set name_de = "Kaffee", mnemonic = "Kaffee mahlen", tag1 ="Lebensmittel", tag2 ="Teil 2" where name = "coffee";
update signs set name_de = "Kalt/Frieren", mnemonic = "Vor Kälte zittern", tag1 ="Eigenschaften", tag2 ="Teil 2" where name = "cold";
update signs set name_de = "Kommen", mnemonic = "Heranwinken", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Verb" where name = "come_here";
update signs set name_de = "Keks", mnemonic = "Abbeißen", tag1 ="Lebensmittel", tag2 ="Teil 1" where name = "cookie";
update signs set name_de = "Kochen", mnemonic = "In Stielkasserolle rühren", tag1 ="Ernährung", tag2 ="Teil 2", tag3 ="Verb" where name = "cooking";
update signs set name_de = "Kuh", mnemonic = "Hörner nachahmen", tag1 ="Tier", tag2 ="Teil 3" where name = "cow";
update signs set name_de = "Gurke", mnemonic = "Gurke nachformen", tag1 ="Lebensmittel", tag2 ="Teil 2" where name = "cucumber";
update signs set name_de = "Schrank", mnemonic = "Mit Handflächen Schrank umreißen", tag1 ="Haus", tag2 ="Teil 2" where name = "cupboard";
update signs set name_de = "Hörgerät", mnemonic = "Hörgerät hinter Ohr mimen", tag1 ="Behinderung", tag2 ="Teil 3" where name = "deaf_aid";
update signs set name_de = "Windel", mnemonic = "Handflächen kletten Windel zu", tag1 ="Körperpflege", tag2 ="Teil 3" where name = "diaper";
update signs set name_de = "Schmutzig", mnemonic = "Krümel auf Hand verteilen", tag1 ="Körperpflege", tag2 ="Teil 2", tag3 ="Eigenschaften" where name = "dirty";
update signs set name_de = "Arzt/Doktor", mnemonic = "Auf Handrücken pieksen", tag1 ="Person", tag2 ="Teil 2" where name = "doctor";
update signs set name_de = "Hund", mnemonic = "Hund zu sich 'heranklopfen'", tag1 ="Tier", tag2 ="Teil 2" where name = "dog";
update signs set name_de = "Puppe", mnemonic = "Baby still auf Arm halten", tag1 ="Spielen", tag2 ="Teil 1" where name = "doll";
update signs set name_de = "Fertig", mnemonic = "Handkante auf Handfläche 'schlagen'", tag1 ="Eigenschaften", tag2 ="Teil 1", tag3 ="Kleine Worte" where name = "done";
update signs set name_de = "Tür/Tor", mnemonic = "Mit gestreckter Hand 'Türöffnen' zeigen", tag1 ="Haus", tag2 ="Teil 2" where name = "door";
update signs set name_de = "Unten/ Tief", mnemonic = "Nach unten zeigen", tag1 ="Kleine Worte", tag2 ="Teil 3", tag3 ="Eigenschaften" where name = "down";
update signs set name_de = "Getränk", mnemonic = "Getränk/Trinkgefäß", tag1 ="Lebensmittel", tag2 ="Teil 1", tag3 ="Getränk" where name = "drink";
update signs set name_de = "Trinken", mnemonic = "Getränk zum Mund führen", tag1 ="Ernährung", tag2 ="Teil 1", tag3 ="Verb" where name = "drinking";
update signs set name_de = "Tropfen", mnemonic = "Zeigefinger tropft (tippen)", tag1 ="Krankheit", tag2 ="Teil 3" where name = "drop";
update signs set name_de = "Essen", mnemonic = "Essen nachahmen", tag1 ="Ernährung", tag2 ="Teil 1", tag3 ="Verb" where name = "eating";
update signs set name_de = "Ei", mnemonic = "Eigröße zeigen", tag1 ="Lebensmittel", tag2 ="Teil 3" where name = "egg";
update signs set name_de = "Leer", mnemonic = "Alles weg", tag1 ="Kleine Worte", tag2 ="Teil 3", tag3 ="Eigenschaften" where name = "empty";
update signs set name_de = "Runterfallen", mnemonic = "Zeige-und Mittelfinger fallen von Handfläche", tag1 ="Freizeit", tag2 ="Teil 3", tag3 ="Verb" where name = "fall_down";
update signs set name_de = "Zuerst", mnemonic = "Daumen taucht von unten auf", tag1 ="Kleine Worte", tag2 ="Teil 2", tag3 ="Zeit" where name = "first";
update signs set name_de = "Fisch", mnemonic = "Hand schlängelt sich durch's Wasser", tag1 ="Tier", tag2 ="Teil 3" where name = "fish";
update signs set name_de = "Blume", mnemonic = "Blüte öffnet sich unter Nase", tag1 ="draußen", tag2 ="Teil 2", tag3 ="Pflanzen" where name = "flower";
update signs set name_de = "Lieb", mnemonic = "Wange 1x von oben nach unten streicheln", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Eigenschaften" where name = "fond";
update signs set name_de = "Fußball spielen", mnemonic = "Faust tritt in Handfläche", tag1 ="Freizeit", tag2 ="Teil 3", tag3 ="Verb" where name = "football";
update signs set name_de = "Gabel", mnemonic = "Gabel piekt in Handfläche", tag1 ="Ernährung", tag2 ="Teil 2" where name = "fork";
update signs set name_de = "Freund/In", mnemonic = "2x Hände schütteln", tag1 ="Person", tag2 ="Teil 1" where name = "friend";
update signs set name_de = "Voll", mnemonic = "Bis oben randvoll", tag1 ="Kleine Worte", tag2 ="Teil 3", tag3 ="Eigenschaften" where name = "full";
update signs set name_de = "Spaß", mnemonic = "2x Nasenspitze stupsen", tag1 ="Interaktion", tag2 ="Teil 3", tag3 ="Freizeit" where name = "fun";
update signs set name_de = "Mädchen", mnemonic = "Mit Daumen 2x Trägerkleid andeuten", tag1 ="Person", tag2 ="Teil 2" where name = "girl";
update signs set name_de = "Geben", mnemonic = "Richtungsgebärde von … zu …", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Verb" where name = "give";
update signs set name_de = "Brille", mnemonic = "Zeigefinger und Daumen formen Brille", tag1 ="Behinderung", tag2 ="Teil 3" where name = "glasses";
update signs set name_de = "weg!", mnemonic = "Wegwerf-Bewegung", tag1 ="Kleine Worte", tag2 ="Teil 1", tag3 ="Eigenschaften" where name = "go_away";
update signs set name_de = "Geh da hin", mnemonic = "Richtung zeigen", tag1 ="Interaktion", tag2 ="Teil 1" where name = "go_there";
update signs set name_de = "Gott", mnemonic = "Dreieinigkeit fährt in den Himmel", tag1 ="Religion", tag2 ="Teil 3" where name = "god";
update signs set name_de = "Gut/Prima", mnemonic = "Daumen hoch", tag1 ="Kleine Worte", tag2 ="Teil 1", tag3 ="Eigenschaften" where name = "good";
update signs set name_de = "Oma", mnemonic = "Dutt andeuten", tag1 ="Person", tag2 ="Teil 2" where name = "grandma";
update signs set name_de = "Opa", mnemonic = "Zwirbelbart andeuten", tag1 ="Person", tag2 ="Teil 2" where name = "grandpa";
update signs set name_de = "Grün", mnemonic = "Grasbüschel wackelt", tag1 ="Farbe", tag2 ="Teil 3", tag3 ="Eigenschaften" where name = "green";
update signs set name_de = "Hallo/Tschüss", mnemonic = "Winken", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Kleine Worte" where name = "hello";
update signs set name_de = "Ich helfe dir", mnemonic = "2. Hand hilft der anderen", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Verb" where name = "helping";
update signs set name_de = "Hier", mnemonic = "Punkt zeigen", tag1 ="Kleine Worte", tag2 ="Teil 1" where name = "here";
update signs set name_de = "Pferd", mnemonic = "Mit Zügeln reiten", tag1 ="Tier", tag2 ="Teil 3" where name = "horse";
update signs set name_de = "Heiß/Warm", mnemonic = "Schweiß von Stirn wischen", tag1 ="draußen", tag2 ="Teil 2", tag3 ="Eigenschaften" where name = "hot";
update signs set name_de = "Haus", mnemonic = "Dach andeuten", tag1 ="Haus", tag2 ="Teil 1" where name = "house";
update signs set name_de = "Ich", mnemonic = "Mit Zeigefinger auf sich zeigen", tag1 ="Person", tag2 ="Teil 1" where name = "i";
update signs set name_de = "Eis", mnemonic = "Eis lecken", tag1 ="Lebensmittel", tag2 ="Teil 2" where name = "ice";
update signs set name_de = "In", mnemonic = "In ein 'Regal' oder in ein 'Gefäß' zeigen", tag1 ="Kleine Worte", tag2 ="Teil 2", tag3 ="Präposition" where name = "in";
update signs set name_de = "Jesus", mnemonic = "Mittelfinger tippen auf Nagelmale", tag1 ="Religion", tag2 ="Teil 3", tag3 ="Person" where name = "jesus";
update signs set name_de = "Saft", mnemonic = "Saft läuft aus gepresster Frucht", tag1 ="Lebensmittel", tag2 ="Teil 2", tag3 ="Getränk" where name = "juice";
update signs set name_de = "Springen/Hüpfen", mnemonic = "Zeige-und Mittelfinger hüpfen auf Handfläche", tag1 ="Freizeit", tag2 ="Teil 3", tag3 ="Verb" where name = "jump";
update signs set name_de = "Kindergarten", mnemonic = "Kinder' und 'Garten' zeigen", tag1 ="Haus", tag2 ="Teil 2", tag3 ="Spielen" where name = "kindergarden";
update signs set name_de = "Küche", mnemonic = "Erst 'kochen' dann 'Zimmer'", tag1 ="Haus", tag2 ="Teil 3" where name = "kitchen";
update signs set name_de = "Messer/Schneiden", mnemonic = "Beide Zeigefinger schneiden", tag1 ="Ernährung", tag2 ="Teil 2", tag3 ="Verb" where name = "knife";
update signs set name_de = "Licht/Lampe", mnemonic = "Strahlende Lampe seitlich oben neben Kopf", tag1 ="Haus", tag2 ="Teil 2" where name = "lamp";
update signs set name_de = "Später", mnemonic = "Wellenförmige Bewegung", tag1 ="Kleine Worte", tag2 ="Teil 2", tag3 ="Zeit" where name = "later";
update signs set name_de = "Hören", mnemonic = "Schall kommt an das Ohr", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Verb" where name = "listening";
update signs set name_de = "Sehen/Gucken", mnemonic = "Richtungsgebärde", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Verb" where name = "look";
update signs set name_de = "Machen", mnemonic = "Obere Faust klopft drehend auf untere Faust", tag1 ="Arbeit", tag2 ="Teil 1", tag3 ="Verb" where name = "make";
update signs set name_de = "Mama", mnemonic = "Wange kreisend streicheln", tag1 ="Person", tag2 ="Teil 1" where name = "mama";
update signs set name_de = "Mann", mnemonic = "Hut an Krempe fassen", tag1 ="Person", tag2 ="Teil 2" where name = "man";
update signs set name_de = "Viele", mnemonic = "Finger zappeln am Kinn zur dominanten Seite", tag1 ="Kleine Worte", tag2 ="Teil 3", tag3 ="Menge" where name = "many";
update signs set name_de = "Marmelade", mnemonic = "Hand streicht flächig auf Brotscheibe", tag1 ="Lebensmittel", tag2 ="Teil 3" where name = "marmelade";
update signs set name_de = "Milch", mnemonic = "Melken", tag1 ="Lebensmittel", tag2 ="Teil 1", tag3 ="Getränk" where name = "milk";
update signs set name_de = "Mehr", mnemonic = "Handfläche bewegt sich nach oben vorn", tag1 ="Kleine Worte", tag2 ="Teil 3", tag3 ="Menge" where name = "more";
update signs set name_de = "Motorrad/Mofa", mnemonic = "An Lenker gibt eine Faust Gas", tag1 ="Fahrzeug", tag2 ="Teil 3" where name = "motorcycle";
update signs set name_de = "Singen/Musik", mnemonic = "Dirigieren", tag1 ="Spielen", tag2 ="Teil 1", tag3 ="Verb" where name = "music";
update signs set name_de = "Nein", mnemonic = "Schnell von einer zur anderen Seite", tag1 ="Kleine Worte", tag2 ="Teil 1", tag3 ="Interaktion" where name = "no";
update signs set name_de = "Nudeln", mnemonic = "Spaghetti aufwickeln", tag1 ="Lebensmittel", tag2 ="Teil 3" where name = "noodles";
update signs set name_de = "Jetzt", mnemonic = "Ich bin die Gegenwart", tag1 ="Kleine Worte", tag2 ="Teil 2", tag3 ="Zeit" where name = "now";
update signs set name_de = "Auf", mnemonic = "Handfläche auf Handrücken legen", tag1 ="Kleine Worte", tag2 ="Teil 2", tag3 ="Präposition" where name = "on_sth";
update signs set name_de = "Eins/Ein", mnemonic = "Zeigefinger und Handrücken zum Gegenüber", tag1 ="Kleine Worte", tag2 ="Teil 1", tag3 ="Menge" where name = "one";
update signs set name_de = "Orange", mnemonic = "Schalen zeigen und herausbrechen", tag1 ="Lebensmittel", tag2 ="Teil 1" where name = "orange";
update signs set name_de = "Draußen", mnemonic = "Nach draußen zeigen", tag1 ="Freizeit", tag2 ="Teil 2", tag3 ="Ort" where name = "outside";
update signs set name_de = "haben/mein", mnemonic = "Handfläche auf Brustkorb legen", tag1 ="Kleine Worte", tag2 ="Teil 3", tag3 ="Verb" where name = "owning";
update signs set name_de = "Schmerzen", mnemonic = "Handfläche vibriert vor Schmerzstelle", tag1 ="Krankheit", tag2 ="Teil 3" where name = "pain";
update signs set name_de = "Malen", mnemonic = "Großflächig in Luft malen", tag1 ="Freizeit", tag2 ="Teil 2", tag3 ="Verb" where name = "painting";
update signs set name_de = "Papa", mnemonic = "Schnauzbart andeuten", tag1 ="Person", tag2 ="Teil 1" where name = "papa";
update signs set name_de = "Papier", mnemonic = "Fäuste klopfen 2x aneinander", tag1 ="Arbeit", tag2 ="Teil 2", tag3 ="Freizeit" where name = "paper";
update signs set name_de = "Bild", mnemonic = "DIN A4-Blatt in die Luft malen", tag1 ="Freizeit", tag2 ="Teil 2", tag3 ="Haus" where name = "picture";
update signs set name_de = "Schwein", mnemonic = "Schnauze nach vorn ziehen", tag1 ="Tier", tag2 ="Teil 3" where name = "pig";
update signs set name_de = "Tablette", mnemonic = "Tablette auf Handfläche malen", tag1 ="Krankheit", tag2 ="Teil 3" where name = "pill";
update signs set name_de = "Rosa/Pink", mnemonic = "Rosa Rose öffnet sich unter Nase", tag1 ="Farbe", tag2 ="Teil 3", tag3 ="Eigenschaften" where name = "pink";
update signs set name_de = "Teller", mnemonic = "Mit Zeigefinger Teller auf Handfläche malen", tag1 ="Ernährung", tag2 ="Teil 2", tag3 ="Geschirr" where name = "plate";
update signs set name_de = "Spielen", mnemonic = "Fächerhände 2x gegengleich auf- und abbewegen", tag1 ="Freizeit", tag2 ="Teil 1", tag3 ="Verb" where name = "playing";
update signs set name_de = "Bitte", mnemonic = "2x Handflächen aneinander", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Kleine Worte" where name = "please";
update signs set name_de = "Sich übergeben", mnemonic = "Den Weg von unten aus Mund heraus", tag1 ="Krankheit", tag2 ="Teil 3", tag3 ="Verb" where name = "puke";
update signs set name_de = "Hase", mnemonic = "Zeige-und Mittelfinger zeigen Ohren", tag1 ="Tier", tag2 ="Teil 3" where name = "rabbit";
update signs set name_de = "Lesen", mnemonic = "Auf Handfläche lesen", tag1 ="Freizeit", tag2 ="Teil 2", tag3 ="Verb" where name = "reading";
update signs set name_de = "Rot", mnemonic = "Lippenrot zeigen", tag1 ="Farbe", tag2 ="Teil 3", tag3 ="Eigenschaften" where name = "red";
update signs set name_de = "Brötchen", mnemonic = "2x Brötchen formen", tag1 ="Lebensmittel", tag2 ="Teil 2" where name = "roll";
update signs set name_de = "Zimmer", mnemonic = "Zeigefinger ziehen Mauer um Zimmer", tag1 ="Haus", tag2 ="Teil 3" where name = "room";
update signs set name_de = "Rennen/Laufen", mnemonic = "Mit Armen 'rennen'", tag1 ="Freizeit", tag2 ="Teil 3", tag3 ="Verb" where name = "run";
update signs set name_de = "Salz", mnemonic = "Prise", tag1 ="Lebensmittel", tag2 ="Teil 3" where name = "salt";
update signs set name_de = "Sand", mnemonic = "Sand aufnehmen und rieseln", tag1 ="Spielen", tag2 ="Teil 2" where name = "sand";
update signs set name_de = "Schule", mnemonic = "Kreide an der Tafel", tag1 ="Arbeit", tag2 ="Teil 2", tag3 ="Haus" where name = "school";
update signs set name_de = "Schere/Schneiden", mnemonic = "Scherbewegung mimen", tag1 ="Freizeit", tag2 ="Teil 2", tag3 ="Arbeit" where name = "scissors";
update signs set name_de = "Schimpfen", mnemonic = "Wie die Geste", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Verb" where name = "scolding";
update signs set name_de = "Rasieren", mnemonic = "Rasierer halten und rasieren mimen", tag1 ="Körperpflege", tag2 ="Teil 3", tag3 ="Verb" where name = "shave";
update signs set name_de = "Schaf", mnemonic = "Wolle am Bauch zeigen", tag1 ="Tier", tag2 ="Teil 3" where name = "sheep";
update signs set name_de = "Schiff/Boot", mnemonic = "Mit Handflächen Bug nach vorn fahren", tag1 ="Fahrzeug", tag2 ="Teil 3" where name = "ship";
update signs set name_de = "Duschen", mnemonic = "Über dem Kopf duschen", tag1 ="Körperpflege", tag2 ="Teil 1", tag3 ="Verb" where name = "showering";
update signs set name_de = "Bruder/Schwester", mnemonic = "Gestreckte Zeigefinger aneinander führen", tag1 ="Person", tag2 ="Teil 1" where name = "sibling";
update signs set name_de = "Krank", mnemonic = "Krallhand klopft 2x auf Brustkorb", tag1 ="Krankheit", tag2 ="Teil 3", tag3 ="Eigenschaften" where name = "sick";
update signs set name_de = "Waschbecken", mnemonic = "Handschüsseln formen Waschbecken", tag1 ="Haus", tag2 ="Teil 3", tag3 ="Körperpflege" where name = "sink";
update signs set name_de = "Sitzen", mnemonic = "Häschenhand zieht von oben nach unten", tag1 ="Arbeit", tag2 ="Teil 1", tag3 ="Verb" where name = "sit";
update signs set name_de = "Klein", mnemonic = "Handflächen 20 cm breit auseinander", tag1 ="Kleine Worte", tag2 ="Teil 3", tag3 ="Eigenschaften" where name = "small";
update signs set name_de = "Etw. anderes", mnemonic = "Zeigefinger deuten viele andere Möglichkeiten an", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Kleine Worte" where name = "something_else";
update signs set name_de = "Löffel", mnemonic = "2x in Mund löffeln", tag1 ="Ernährung", tag2 ="Teil 2", tag3 ="Besteck" where name = "spoon";
update signs set name_de = "Stehen", mnemonic = "Zeige-und Mittelfinger  stehen auf Handfläche", tag1 ="Alltag", tag2 ="Teil 1", tag3 ="Verb" where name = "stand";
update signs set name_de = "Aufstehen", mnemonic = "Wie der Pfarrer in der Kirche", tag1 ="Alltag", tag2 ="Teil 1", tag3 ="Verb" where name = "stand_up";
update signs set name_de = "Stopp", mnemonic = "Halt zeigen", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Kleine Worte" where name = "stop";
update signs set name_de = "Zucker", mnemonic = "Erst 'süß' zeigen, dann mit Fingern streuen", tag1 ="Lebensmittel", tag2 ="Teil 3" where name = "sugar";
update signs set name_de = "Schwimmen", mnemonic = "Brustschwimmen mimen", tag1 ="Freizeit", tag2 ="Teil 3", tag3 ="Verb" where name = "swimming";
update signs set name_de = "Etw. ausschalten", mnemonic = "Klappe zu!", tag1 ="Eigenschaften", tag2 ="Teil 1", tag3 ="Verb" where name = "switch_off";
update signs set name_de = "Etw. anschalten", mnemonic = "Daumen drückt Schalter", tag1 ="Eigenschaften", tag2 ="Teil 1", tag3 ="Verb" where name = "switch_on";
update signs set name_de = "Tisch", mnemonic = "Tischfläche von innen nach außen streichen", tag1 ="Haus", tag2 ="Teil 1" where name = "table";
update signs set name_de = "Tee", mnemonic = "Teebeutel auf-und abschwenken", tag1 ="Lebensmittel", tag2 ="Teil 2", tag3 ="Getränk" where name = "tea";
update signs set name_de = "Telefon", mnemonic = "Y-Hand an Ohr", tag1 ="Interaktion", tag2 ="Teil 2", tag3 ="Alltag" where name = "telephone";
update signs set name_de = "Danke", mnemonic = "Wie die Queen; vom Kinn aus nach vorn", tag1 ="Interaktion", tag2 ="Teil 1" where name = "thank_you";
update signs set name_de = "Da", mnemonic = "Zeigen", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Kleine Worte" where name = "there";
update signs set name_de = "Denken/Schlau", mnemonic = "Mit Zeigefinger auf Kopf tippen", tag1 ="Arbeit", tag2 ="Teil 2", tag3 ="Verb" where name = "thinking";
update signs set name_de = "Aufräumen", mnemonic = "3x einen Stapel zusammenschieben", tag1 ="Spielen", tag2 ="Teil 1", tag3 ="Verb" where name = "tidy_up";
update signs set name_de = "Winzig/Wenig", mnemonic = "Zeigefinger und Daumen zeigen 'wenig'", tag1 ="Kleine Worte", tag2 ="Teil 3", tag3 ="Menge" where name = "tiny";
update signs set name_de = "Heute", mnemonic = "2x langsam vor sich nach unten zeigen", tag1 ="Zeit", tag2 ="Teil 3" where name = "today";
update signs set name_de = "Toilette", mnemonic = "Y-Hand dreht neben Kopf", tag1 ="Körperpflege", tag2 ="Teil 1", tag3 ="Alltag" where name = "toilet";
update signs set name_de = "Tomate", mnemonic = "Tomate vom Busch abdrehen", tag1 ="Lebensmittel", tag2 ="Teil 2" where name = "tomato";
update signs set name_de = "Morgen", mnemonic = "Großen Bogen nach vorn zeigen", tag1 ="Zeit", tag2 ="Teil 3" where name = "tomorrow";
update signs set name_de = "Handtuch", mnemonic = "Handtuch mit Zeigefinger umfahren", tag1 ="Körperpflege", tag2 ="Teil 3" where name = "towel";
update signs set name_de = "Kuscheltier", mnemonic = "Kuscheln zeigen", tag1 ="Spielen", tag2 ="Teil 2" where name = "toy";
update signs set name_de = "Zug/Eisenbahn", mnemonic = "Neben Körper Räderdrehen zeigen", tag1 ="Fahrzeug", tag2 ="Teil 3", tag3 ="Spielen" where name = "train";
update signs set name_de = "Baum", mnemonic = "Arm=Baumstamm, Finger=Äste", tag1 ="draußen", tag2 ="Teil 2", tag3 ="Pflanzen" where name = "tree";
update signs set name_de = "Hinfallen", mnemonic = "Nach vorn abstützen", tag1 ="Alltag", tag2 ="Teil 3", tag3 ="Verb" where name = "tumbling";
update signs set name_de = "Fernseher/Fernsehen", mnemonic = "Fernbedienung tippen", tag1 ="Haus", tag2 ="Teil 2", tag3 ="Freizeit" where name = "tv";
update signs set name_de = "Zwei", mnemonic = "Zwei Finger", tag1 ="Kleine Worte", tag2 ="Teil 1", tag3 ="Menge" where name = "two";
update signs set name_de = "Oben/Hoch", mnemonic = "Nach oben zeigen", tag1 ="Kleine Worte", tag2 ="Teil 3" where name = "up";
update signs set name_de = "Warte/Langsam", mnemonic = "verlangsamende Bewegung", tag1 ="Eigenschaften", tag2 ="Teil 1", tag3 ="Verb" where name = "wait";
update signs set name_de = "Gehen", mnemonic = "Zeige-und Mittelfinger spazieren", tag1 ="Alltag", tag2 ="Teil 3", tag3 ="Verb" where name = "walk";
update signs set name_de = "Waschen", mnemonic = "Hände waschen sich", tag1 ="Körperpflege", tag2 ="Teil 1" where name = "washing";
update signs set name_de = "Wasser", mnemonic = "Steht mir bis zum Hals", tag1 ="Lebensmittel", tag2 ="Teil 1", tag3 ="Getränk" where name = "water";
update signs set name_de = "Wir", mnemonic = "Auf alle und sich selbst zeigen", tag1 ="Personen", tag2 ="Teil 1", tag3 ="Kleine Worte" where name = "we";
update signs set name_de = "Was?", mnemonic = "Handflächen hin und her schütteln", tag1 ="Frage", tag2 ="Teil 1" where name = "what";
update signs set name_de = "Wann?", mnemonic = "Finger klopfen ungeduldig an Wange", tag1 ="Frage", tag2 ="Teil 3" where name = "when";
update signs set name_de = "Wo?", mnemonic = "Schüssel mit Händen nachahmen", tag1 ="Frage", tag2 ="Teil 1" where name = "where";
update signs set name_de = "Wer?", mnemonic = "Fingeralphabet-R wackelt", tag1 ="Frage", tag2 ="Teil 3" where name = "who";
update signs set name_de = "Fenster", mnemonic = "Mit Zeigefingern Fenster in Luft malen", tag1 ="Haus", tag2 ="Teil 2" where name = "window";
update signs set name_de = "Mit", mnemonic = "Daumen kommt mit anderen Fingern mit", tag1 ="Kleine Worte", tag2 ="Teil 2" where name = "with";
update signs set name_de = "Frau", mnemonic = "Ohrring", tag1 ="Person", tag2 ="Teil 2" where name = "woman";
update signs set name_de = "Stift/Schreiben", mnemonic = "Mit Stift schreiben mimen", tag1 ="Arbeit", tag2 ="Teil 2", tag3 ="Verb" where name = "writing";
update signs set name_de = "Gelb", mnemonic = "Y-Hand (Yellow) dreht im Handgelenk", tag1 ="Farbe", tag2 ="Teil 3", tag3 ="Eigenschaften" where name = "yellow";
update signs set name_de = "Ja", mnemonic = "Nicken", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Kleine Worte" where name = "yes";
update signs set name_de = "Gestern", mnemonic = "Großen Bogen  nach hinten zeigen", tag1 ="Zeit", tag2 ="Teil 3" where name = "yesterday";
update signs set name_de = "Joghurt", mnemonic = "Becher auslöffen", tag1 ="Lebensmittel", tag2 ="Teil 2" where name = "yoghurt";
update signs set name_de = "Du", mnemonic = "mit Zeigefinger auf Gegenüber zeigen", tag1 ="Person", tag2 ="Teil 1", tag3 ="Kleine Worte" where name = "you";
update signs set name_de = "Du hilfst Mir", mnemonic = "2. Hand hilft der anderen", tag1 ="Interaktion", tag2 ="Teil 1", tag3 ="Verb" where name = "you_help_me";
update signs set name_de = "Dein", mnemonic = "Handfläche zeigt langsam auf Gesprächspartner", tag1 ="Kleine Worte", tag2 ="Teil 3" where name = "yours";
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("evening","Abend","Handflächen legen sich von außen kommend übereinander","Zeit","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("old","alt","mit Zügelhand kleines Stück an Wange runtersteichen","Eigenschaften","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("anxiety","Angst","Faust klopft an Herz; Herzklopfen vor Angst","Gefühl","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("here_you_are","Bitte schön","Flachhand bietet etwas an","Interaktion","Zusatz","Kleine Worte");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("bossmang","Chef","Gut'-Faust steigt von anderem Handrücken auf","Person","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("computer","Computer","Zehn Finger tippen auf Tastatur","Arbeit","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("morning","der Morgen","es wird hell'","Zeit","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("tuesday","Dienstag","mit Pinzettengriff an Wange 1x drehen","Wochentag","Zusatz","Zeit");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("thursday","Donnerstag","Blitzschnell mit Zeigefinger neben dem Kopf","Wochentag","Zusatz","Zeit");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("allowed","dürfen","Flachhand kippt nach vorn","Verb","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("surprise","erschrecken","gespreizte Hände fliegen plötzlich nach außen (Mimik!)","Gefühl","Zusatz","Verb");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("drive","fahren","parallele Pistolenhände fahren diagonal nach vorn","Fahrzeug","Zusatz","Verb");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("friday","Freitag","Zeigefinger von Nasenspitze an Stirn drehen","Wochentag","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("happiness","Freude","Handflächen wedeln aufsteigende Freude vor dem Bauch","Gefühl","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("happy","fröhlich","Handflächen wedeln aufsteigende Freude vor dem Bauch","Gefühl","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("spring","Frühling","sich öffnende Blume seitlich auf Schulterhöhe","Jahreszeit","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("birthday","Geburtstag","erstes Herzklopfen mit der Faust zeigen","Freizeit","Zusatz","feiern");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("soon","gleich","gestreckte Zeigefinger parallel 2x aneinderstoßen","Kleine Worte","Zusatz","Eigenschaften");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("autumn","Herbst","Gegenbewegung zu Frühling: Pflanzen verschwinden wieder in Erde (Blumenzwiebeln, Stauden..)","Jahreszeit","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("fetch","holen","offene Hand zieht etwas zu sich heran","Alltag","Zusatz","Verb");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("you_plural","ihr","in Bogen auf die anderen zeigen","Person","Zusatz","Kleine Worte");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("always","immer","große Spaghetti nach vorn wickeln","Kleine Worte","Zusatz","Zeit");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("cake","Kuchen","Blech mit flachen Händen in Ofen schieben","Lebensmittel","Zusatz","Freizeit");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("slow","langsam","flache Hände 2x langsam vor Körper senken","Eigenschaften","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("loud","laut","beide C-Hände von den Ohren wegführen","hören","Zusatz","Eigenschaften");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("quiet","leise","Zeigefinger auf geschlossenen Lippen","hören","Zusatz","Eigenschaften");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("learn","lernen","Schnabelhand 'füttert' Hirn - an Schläfe","Arbeit","Zusatz","Verb");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("wednesday","Mittwoch","Pistolenhand 2x an Kinn tupfen","Wochentag","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("monday","Montag","Daumennagel streicht an Wange runter","Wochentag","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("night","Nacht","Handflächen schließen zu Fäusten","Zeit","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("name","Name","Zeige-und Mittelfinger 3x an Wange  klopfen","Person","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("brand_new","neu","dominante Hand schiebt sich langsam hinter anderer Hand hervor: 'neu erscheinen'","Kleine Worte","Zusatz","Eigenschaften");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("never","nie","Zeigefinger-X schnell auseinanderziehen","Kleine Worte","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("pause","Pause","Glocke läuten zeigen","Arbeit","Zusatz","Alltag");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("calculate","rechnen","alle Finger wackeln (Zählfinger)","Arbeit","Zusatz","Verb");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("saturday","Samstag","mit Handrücken 'Lächeln' unter Kinn zeigen","Wochentag","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("fast","schnell","Faust schnell nach vorn mit plötzlichem Stopp","Kleine Worte","Zusatz","Eigenschaften");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("summer","Sommer","wie 'warm'","Jahreszeit","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("sunday","Sonntag","'schicke Kleidung' mit Handstreichen über Oberkörper zeigen","Wochentag","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("tablet","Tablet","Zeige wischt auf Tablet/Handfläche","Arbeit","Zusatz","Interaktion");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("day","Tag","beide Pinzettengriffe ziehen Tag wie Kaugummi auseinander","Zeit","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("sad","traurig","Krallenhand zeigt 'Herzschmerz' (Kreisen +Mimik!)","Gefühl","Zusatz","Eigenschaften");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("forget","vergessen","Flachhand zieht etwas aus dem Gedächtnis/ Kopf","Interaktion","Zusatz","Verb");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("different","verschieden","V-Hände gegengleich vor Körper senken und heben","Kleine Worte","Zusatz","Eigenschaften");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("why","warum","bohrender Zeigefinger (bohrende Frage)","Frage","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("which","welche","eine Flugzeug-Hand 3x wackeln","Frage","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("how_many","wie viele","zappelnde Finger einer Hand neben Schulter","Frage","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("how","wie","Flugzeug-Hände; kleine Finger überkreuz auseinanderziehen","Frage","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2) values ("winter","Winter","wie 'kalt'","Jahreszeit","Zusatz");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("week","Woche","C-Hand von nichtdominanter zu dominanter Seite ziehen (Dauer anzeigen)","Zeit","Zusatz","Wochentage");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("want","wollen","Flachhand 1x an Herz schlagen","Alltag","Zusatz","Verb");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("angry","wütend","Fäuste zittern vor Wut neben Schultern","Gefühl","Zusatz","Eigenschaften");
insert into signs (name, name_de, mnemonic, tag1, tag2, tag3) values ("together","zusammen","von außen mit offenen Handflächen alles zusammenballen","Kleine Worte","Zusatz","Eigenschaften");